# Generated by Django 5.1.5 on 2025-03-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=50)),
                ('Crop', models.CharField(max_length=50)),
                ('Area', models.FloatField()),
                ('Budget', models.FloatField()),
                ('StartDate', models.DateField()),
            ],
        ),
    ]
