# Generated by Django 5.1.5 on 2025-03-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_expenditure_date_income_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crop',
            new_name='Farm',
        ),
    ]
