# Generated by Django 5.1.5 on 2025-03-14 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_crop_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='farm_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='farm_id',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.farm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='farm',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.farm'),
            preserve_default=False,
        ),
    ]
